# Generated by Django 2.2.2 on 2019-06-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0003_auto_20190614_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='box_type',
        ),
        migrations.AddField(
            model_name='product',
            name='box_type',
            field=models.IntegerField(default=1),
        ),
    ]
