# Generated by Django 2.2.2 on 2019-06-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0005_auto_20190617_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='box_type',
            field=models.IntegerField(null=True),
        ),
    ]
