# Generated by Django 2.2.2 on 2019-07-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0006_auto_20190617_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='box_dimension',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='box_weight',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='one_pc_weight',
            field=models.FloatField(null=True),
        ),
    ]
