# Generated by Django 2.2.2 on 2019-08-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0007_auto_20190709_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='box_dimension',
        ),
        migrations.AddField(
            model_name='product',
            name='box_size_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='box_size_2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
